branch-defaults:
  master:
    environment: stellaroute-dev
    group_suffix: null
global:
  application_name: stellaroute
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  profile: null
  sc: git
